"""Chenges

Revision ID: c48c66155715
Revises: d602c5b6a30a
Create Date: 2025-01-11 16:16:47.184068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c48c66155715'
down_revision: Union[str, None] = 'd602c5b6a30a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('order_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'products', 'orders', ['order_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'order_id')
    # ### end Alembic commands ###
