UPPER_CASE_LETTERS = 'ABCDEFGHIGKLMNOPQRSTUVWXYZ'
LOWER_CASE_LETTERS = 'abcdefghigklmnopqrstuvwxyz'
NUMBERS = '1234567890'
SYMBOLS = '#$@/.'
ALL_SYMBOLS = UPPER_CASE_LETTERS + LOWER_CASE_LETTERS + NUMBERS + SYMBOLS
